### ISSUE TITLE
Error when running process_folder locally and with travis

### ISSUE THREAD

**Issue by mkschleg** [JuliaCI/Coverage.jl#247] opened 2019-10-13 20:33 UTC
I'm running into the following error when using the function `process_folder()` both locally and when using travis using Coverage.jl v0.9.3. I'm not sure if I'm missing a step in the process, but I think I'm following the instructions in the README correctly.

I'm creating the *.cov files through `Pkg.test("Reproduce", coverage=true)` if this matters.

```
[ Info: Coverage.process_folder: Searching src for .jl files...
[ Info: Coverage.process_file: Detecting coverage for src/Reproduce.jl
[ Info: Coverage.process_cov: processing src/Reproduce.jl.64441.cov
[ Info: Coverage.process_file: Detecting coverage for src/args_iter.jl
[ Info: Coverage.process_cov: processing src/args_iter.jl.64440.cov
[ Info: Coverage.process_file: Detecting coverage for src/args_looper.jl
[ Info: Coverage.process_cov: processing src/args_looper.jl.64440.cov
[ Info: Coverage.process_file: Detecting coverage for src/exp_utils.jl
┌ Info: Coverage.process_cov: Coverage file(s) for src/exp_utils.jl do not exist.
└ Assuming file has no coverage.
[ Info: Coverage.process_file: Detecting coverage for src/parallel_experiment.jl
┌ Info: Coverage.process_cov: Coverage file(s) for src/parallel_experiment.jl do not exist.
└ Assuming file has no coverage.
[ Info: Coverage.process_file: Detecting coverage for src/parse.jl
[ Info: Coverage.process_cov: processing src/parse.jl.64440.cov
[ Info: Coverage.process_file: Detecting coverage for src/plot_utils.jl
┌ Info: Coverage.process_cov: Coverage file(s) for src/plot_utils.jl do not exist.
└ Assuming file has no coverage.
[ Info: Coverage.process_file: Detecting coverage for src/save.jl
┌ Info: Coverage.process_cov: Coverage file(s) for src/save.jl do not exist.
└ Assuming file has no coverage.
[ Info: Coverage.process_file: Detecting coverage for src/search.jl
[ Info: Coverage.process_cov: processing src/search.jl.64440.cov
[ Info: Coverage.process_file: Detecting coverage for src/search_utils.jl
┌ Info: Coverage.process_cov: Coverage file(s) for src/search_utils.jl do not exist.
└ Assuming file has no coverage.
ERROR: Base.Meta.ParseError("extra token \"save\" after end of expression")
Stacktrace:
 [1] #parse#1(::Bool, ::Bool, ::Bool, ::Function, ::String, ::Int64) at ./meta.jl:129
 [2] parse(::String, ::Int64) at ./meta.jl:121
 [3] amend_coverage_from_src!(::FileCoverage) at /Users/Matt/.julia/packages/Coverage/hf37Q/src/Coverage.jl:189
 [4] process_file(::String, ::String) at /Users/Matt/.julia/packages/Coverage/hf37Q/src/Coverage.jl:221
 [5] process_folder(::String) at /Users/Matt/.julia/packages/Coverage/hf37Q/src/Coverage.jl:244
 [6] process_folder() at /Users/Matt/.julia/packages/Coverage/hf37Q/src/Coverage.jl:236
 [7] top-level scope at none:0
```

**Comment by DilumAluthge** [comment] 2019-11-10 00:23
@mkschleg I believe that this issue is caused by a typo in your source code. Can you merge https://github.com/mkschleg/Reproduce.jl/pull/43 and see if this fixes your issue?

**Comment by DilumAluthge** [comment] 2019-11-10 06:20
@mkschleg I looked at the Travis logs (https://travis-ci.com/mkschleg/Reproduce.jl/builds/135796854) for https://github.com/mkschleg/Reproduce.jl/pull/43.

The Travis logs seem to suggest that https://github.com/mkschleg/Reproduce.jl/pull/43 fixes this issue for you.

I am going to close this issue. Let me know if merging https://github.com/mkschleg/Reproduce.jl/pull/43 does not fix this issue for you.

**Closed by DilumAluthge** 2019-11-10 06:20 UTC
Labels: awaiting response, invalid

**Comment by mkschleg** [comment] 2019-11-10 19:47
Thanks for helping with this.
