### ISSUE TITLE
Coverage missing lines 

### ISSUE THREAD

**Issue by somil55** [JuliaCI/Coverage.jl#172] opened 2018-07-31 17:37 UTC
Codecov is showing missing coverage for few lines but the next executed line has coverage.
https://codecov.io/gh/JuliaGraphs/LightGraphs.jl/compare/da7e055a3173859a294e657be9ac85e10f3a5087...d7ee43a28459f3a6533116a5905d8dd5c44fcd0c/diff

**Comment by SohamTamba** [comment] 2018-07-31 19:29
```@inbounds for s in source
        0         vert_level[s] = zero(T)
        0         visited[s] = true
       14         push!(cur_level, s)
        -     end
```
Some lines are marked as `0` when they should be marked as `-`

**Comment by fingolfin** [comment] 2019-03-05 13:39
@somil55 The link you gave is broken. (I'd recommend in general to always write self-contained issue descriptions, and only use links to provide additional information or examples).

Without further information on what the issue is / how to reproduce it, I am afraid there is nothing we can do to help. I am therefore closing this now. Please feel free to re-open it should you be able to provide additional information (including working links). Thank you!

**Closed by fingolfin** 2019-03-05 13:39 UTC
